### ISSUE TITLE
Unable to build on latest master

### ISSUE THREAD

**Issue by bhankas** [CeleritasCelery/rune#108]
Getting below errors:

```
~/g/rune master ❱ cargo run --release -- --repl
   Compiling rune v0.1.0 (/home/payas/git/rune)
error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/core/object/symbol.rs:89:19
   |
89 |         let ptr = core::ptr::without_provenance(idx * size_of::<SymbolCell>());
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
   --> src/core/object/tagged.rs:766:9
    |
766 |         core::ptr::without_provenance(value as usize)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
    --> src/core/object/tagged.rs:1110:19
     |
1110 |         let ptr = core::ptr::without_provenance(x);
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/core/object/symbol.rs:63:49
   |
63 |             let base = BUILTIN_SYMBOLS.as_ptr().addr();
   |                                                 ^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/core/object/symbol.rs:64:33
   |
64 |             let ptr = self.data.map_addr(|x| x.wrapping_add(base)).cast::<SymbolCell>();
   |                                 ^^^^^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/core/object/symbol.rs:67:44
   |
67 |                 &*BUILTIN_SYMBOLS.as_ptr().with_addr(ptr.addr())
   |                                            ^^^^^^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/core/object/symbol.rs:67:58
   |
67 |                 &*BUILTIN_SYMBOLS.as_ptr().with_addr(ptr.addr())
   |                                                          ^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/core/object/symbol.rs:83:45
   |
83 |         let base = BUILTIN_SYMBOLS.as_ptr().addr();
   |                                             ^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/core/object/symbol.rs:84:23
   |
84 |         let ptr = ptr.map_addr(|x| (x.wrapping_sub(base)));
   |                       ^^^^^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/core/object/tagged.rs:77:36
   |
77 |         let ptr = ptr.cast::<u8>().map_addr(|x| (x << 8) | tag as usize);
   |                                    ^^^^^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/core/object/tagged.rs:82:28
   |
82 |         let ptr = self.ptr.map_addr(|x| ((x as isize) >> 8) as usize);
   |                            ^^^^^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/core/object/tagged.rs:88:47
   |
88 |         unsafe { std::mem::transmute(self.ptr.addr() as u8) }
   |                                               ^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
   --> src/core/object/tagged.rs:760:13
    |
760 |         ptr.addr() as i64
    |             ^^^^
    |
    = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/bytecode.rs:33:70
   |
33 |         ProgramCounter { range: vec.as_ptr_range(), pc: vec.as_ptr().map_addr(|a| a + offset) }
   |                                                                      ^^^^^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/bytecode.rs:37:17
   |
37 |         self.pc.addr() - self.range.start.addr()
   |                 ^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

error[E0658]: use of unstable library feature 'strict_provenance'
  --> src/bytecode.rs:37:43
   |
37 |         self.pc.addr() - self.range.start.addr()
   |                                           ^^^^
   |
   = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rune` (bin "rune") due to 16 previous errors
```

I am not super familiar with Rust, so would like to understand if I'm invoking the wrong command before trying to fix this.

**Comment by bhankas** [comment]
Nvm, my cargo/rustc were old. After upgrading to 1.84.0 am able to build and test.
